{{- define "bitwarden.serviceUrl" -}}
http://bitwarden-cli.{{ .Release.Namespace }}.svc.cluster.local:8087
{{- end -}}

{{- define "bitwarden.remotePlaceholder" -}}
{{ print "{{" }} .remoteRef.{{ . }} {{ print "}}" }}
{{- end -}}

---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-login
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: bitwarden-external-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    webhook:
      url: '{{ template "bitwarden.serviceUrl" . }}/object/item/{{ template "bitwarden.remotePlaceholder" "key" }}'
      headers:
        Content-Type: application/json
      result:
        jsonPath: '$.data.login.{{ template "bitwarden.remotePlaceholder" "property" }}'
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-fields
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: bitwarden-external-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    webhook:
      url: '{{ template "bitwarden.serviceUrl" . }}/object/item/{{ template "bitwarden.remotePlaceholder" "key" }}'
      result:
        jsonPath: '$.data.fields[?@.name=="{{ template "bitwarden.remotePlaceholder" "property" }}"].value'
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-notes
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: bitwarden-external-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    webhook:
      url: '{{ template "bitwarden.serviceUrl" . }}/object/item/{{ template "bitwarden.remotePlaceholder" "key" }}'
      result:
        jsonPath: '$.data.notes'
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-ssh-key
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: bitwarden-external-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  provider:
    webhook:
      url: '{{ template "bitwarden.serviceUrl" . }}/object/item/{{ template "bitwarden.remotePlaceholder" "key" }}'
      result:
        jsonPath: '$.data.sshKey.{{ template "bitwarden.remotePlaceholder" "property" }}'
